# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

# name: Electron Packager

#on:
#  push:
 #   branches: [ "main" ]
  #pull_request:
#    branches: [ "main" ]

#jobs:
#  build:

#    runs-on: ubuntu-latest

 #   strategy:
  #    matrix:
   #     node-version: [18.x, 20.x]
    #    # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

  #  steps:
   # - uses: actions/checkout@v3
 #   - name: Use Node.js ${{ matrix.node-version }}
  #    uses: actions/setup-node@v3
   #   with:
#        node-version: ${{ matrix.node-version }}
#        cache: 'npm'
 #   - run: echo "::set-output name=zip-name::$(jq -r .productName package.json)"
  #  - run: npm i electron-packager@latest
#    - run: sudo dpkg --add-architecture i386 && wget -qO - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add - && sudo add-apt-repository ppa:cybermax-dexter/sdl2-backport && sudo apt-add-repository "deb https://dl.winehq.org/wine-builds/ubuntu $(lsb_release -cs) main" && sudo apt install --install-recommends winehq-stable
   # - run: npx electron-packager . --arch=arm64 --platform=linux --icon=icon.png --overwrite
  #  - run: npx electron-packager . --arch=x86 --platform=linux --icon=icon.png --overwrite
   # - run: npx electron-packager . --arch=x86_64 --platform=linux --icon=icon.png --overwrite
  #  - run: npx electron-packager . --arch=armv7l --platform=linux --icon=icon.png --overwrite
   # - run: npx electron-packager . --arch=mips64el --platform=linux --icon=icon.png --overwrite
  #  - run: wget
   # - run: zip -r -q ${{ steps.read-package.outputs.zip-name }}-linux-arm64.zip ${{ steps.read-package.outputs.zip-name }}-linux-arm64/
  #  - run: zip -r -q ${{ steps.read-package.outputs.zip-name }}-linux-x64.zip ${{ steps.read-package.outputs.zip-name }}-linux-x64/
